{{- if .Values.devRunner.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-dev-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.devRunner.config }}
  {{ $key }}: |-
    {{- $value | toString | nindent 4 }}
  {{- end }}
{{- end }}
